### ISSUE TITLE
License of Project

### ISSUE THREAD

**Issue by pmouawad** [jetty-project/jetty-alpn#10]
Hello,
Thanks for this project.
I'd like to know under which License this project is distributed ?

Apache ?
LGPL ?
BSD ?
...

Thank you

**Comment by joakime** [comment]
As with most maven projects, check the `pom.xml` for a `<licenses>` element.

https://github.com/jetty-project/jetty-alpn/blob/master/pom.xml#L35-L44

This project, the `jetty-alpn` project, is ...

```xml
    <licenses>
        <license>
            <name>Apache License Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0</url>
        </license>
        <license>
            <name>GPL v2 with ClassPath Exception</name>
            <url>http://openjdk.java.net/legal/gplv2+ce.html</url>
        </license>
    </licenses>
```

**Comment by pmouawad** [comment]
Thank you for your quick answer.
I don't understand clearly what "GPL v2 with ClassPath Exception" means.

Thank you in advance

**Comment by joakime** [comment]
Follow the URL, it has the text for that license.

**Comment by pmouawad** [comment]
Thank you.
I read it but it is not my question.

I want to know under which license your project is licensed ?
Apache or GPL v2 with ClassPath Exception? Or is it available under the 2 licenses ? 

Sorry if my question is stupid.
Regards

**Comment by pmouawad** [comment]
Maybe this applies (found at http://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-license-details):

_The ALPN implementation relies on modification of a few OpenJDK classes and on a few new classes that need to live in the sun.security.ssl package. These classes are released under the same GPLv2+exception license of OpenJDK.

The ALPN class and its nested classes are released under same license as the classes of the Jetty project._

**Comment by sbordet** [comment]
That is correct.

**Comment by pmouawad** [comment]
Thanks
