### ISSUE TITLE
Compile error with Oracle JDK 8u121

### ISSUE THREAD

**Issue by sehaas** [jetty-project/jetty-alpn#11]
alpn-boot does not compile with jdk8u121 because some method/variable/constructor where removed in `sun.security.ssl.SupportedEllipticCurvesExtension` and `sun.security.ssl.ECDHCrypt`.

You can find my maven output here: [compile_error_e_jdk8u121.txt](https://github.com/jetty-project/jetty-alpn/files/713878/compile_error_e_jdk8u121.txt)

The build worked with older jdk versions.

**Comment by joakime** [comment]
See also eclipse/jetty.project#1273

**Comment by sbordet** [comment]
Fixed by ae6c52119acf8515d5911a904a5756623c0f623f.

**Comment by sehaas** [comment]
Thank you for the fast support.
