### ISSUE TITLE
1.8.0_131 support

### ISSUE THREAD

**Issue by ben-manes** [jetty-project/jetty-alpn#12]
And `jetty-alpn-agent`, of course. The current version works with JDKs up to 121.

**Comment by sbordet** [comment]
The current version works with 131 as well.
See https://www.eclipse.org/jetty/documentation/9.4.x/alpn-chapter.html#alpn-versions.

**Comment by ben-manes** [comment]
hmm, then do you know why I receive the following error on that JDK version (ubuntu) but not on 1.8.0_111 (macbook)?

```
ERROR [2017-07-12 21:34:49,000] [org.mortbay.jetty.alpn.agent.Util] [jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker
ERROR [2017-07-12 21:34:49,006] [org.mortbay.jetty.alpn.agent.Util] [jetty-alpn-agent] Replacing: sun/security/ssl/HelloExtensions
ERROR [2017-07-12 21:34:49,010] [org.mortbay.jetty.alpn.agent.Util] [jetty-alpn-agent] Replacing: sun/security/ssl/ExtensionType
ERROR [2017-07-12 21:34:49,037] [org.mortbay.jetty.alpn.agent.Util] [jetty-alpn-agent] Replacing: sun/security/ssl/ClientHandshaker$2
```

**Comment by joakime** [comment]
What version of Jetty?

**Comment by ben-manes** [comment]
9.4.6.v20170531

**Comment by ben-manes** [comment]
Yes, I thought the agent needed an updated version of `jetty-alpn` since 131 wasn't in `Premain`, so I posted it here. Bad assumption.

Thanks. I use SysOutOverSLF4J to pipe to the logs, so that explains it. I was surprised that nothing broke.
