### ISSUE TITLE
Unexpected http request response

### ISSUE THREAD

**Issue by ogolovanov** [jetty-project/jetty-alpn#28]
Hello!

I do not really know where should i ask question like that.

Test url: "https://yandex.ru/"
Java http client: okhttp

Problem:
if i request that url via latest jdk8 ( 8u221 ) and latest alpn ( alpn-boot-8.1.13.v20181017.jar ) -> i get 403 response.
if i run absolutely the same code via jdk 8u152 and alpn ( alpn-boot-8.1.11.v20170118.jar ) -> i get 200 response as expected.

In both cases request goes via http2 ( as expected ).

I am very interested - how can that be possible?
If i use another test url ( e.g. "https://www.google.ru" ) -> i always get success response ( as expected ).
If i do not use alpn ( and, respectively, http2 ) -> request goes via http1.1 -> also success response with both java versions.

What do you think?
Thanks.

**Comment by ogolovanov** [comment]
Small update:

problem starts from java 8u171.
there is no such problem ( 403 response ) with java 8u162 although alpn version is the same.

hmm.

**Comment by sbordet** [comment]
@ogolovanov ALPN happens during the TLS handshake.
If you get a 403, it means that the TLS handshake completed successfully, you were able to send the request and to receive the response from the server.
I don't know why you get the 403, but it's not related to ALPN.
Could be that the server is throttling you.

**Comment by ogolovanov** [comment]
But how can that be possible at all, that absolutely the same code gives absolutely different result with different version of java + alpn? ( and in both cases request goes via http2 ) ?

**Comment by sbordet** [comment]
You should ask the server, not this project.
403 is a clear HTTP response that means "Forbidden".
The server received and understood perfectly your request _because ALPN worked_.
But it decided to forbid the content to your client.
And the client received the 403 correctly. 
All is working from the ALPN point of view.
Maybe it was just a transitory problem on the server.

**Comment by ogolovanov** [comment]
Thank you!
Last question, please: does web server knows anything about client's alpn version?

**Comment by sbordet** [comment]
ALPN has no versions.
The server knows that the client used ALPN and it also uses ALPN to communicate to the client what's the application protocol that has been negotiated.
