### ISSUE TITLE
Jetty-alpn 8.1.13 is incompatible with the latest jdk8u252-ga build

### ISSUE THREAD

**Issue by jguo11** [jetty-project/jetty-alpn#30]
Hi,

I find out Jetty-alpn 8.1.13 is incompatible with the latest jdk8u252-ga available at 04/14. The Jetty-alpn fails to build due to null session object `static final SSLSessionImpl nullSession` has been removed from `SSLSessionImpl` class since [8u252](https://hg.openjdk.java.net/jdk8u/jdk8u/jdk/file/e6178063e9dd/src/share/classes/sun/security/ssl/SSLSessionImpl.java#l75).

```
    [javac]src/sun/security/ssl/ClientHandshaker.java:1350: error: cannot find symbol
    [javac]         SessionId sessionId = SSLSessionImpl.nullSession.getSessionId();
    [javac]                                             ^
    [javac]   symbol:   variable nullSession
```

**Comment by sbordet** [comment]
The Java 9 ALPN classes have been backported to OpenJDK 8u252, so there is no more need for this project.
See the updated README in the project front page.
